apiVersion: v1
kind: Service
metadata:
  name: pronosana-prometheus-service
  namespace: pronosana
  labels:
    run: pronosana-prometheus-service
spec:
  type: NodePort
  ports:
  - port: 9090
    targetPort: 9090
    nodePort: 30000
    protocol: TCP
    name: prom-port
  selector:
    app: pronosana