apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pronosana-pv-claim
  namespace: pronosana
spec:
  storageClassName: manual
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi