apiVersion: v1
kind: PersistentVolume
metadata:
  name: pronosana-pv
  namespace: pronosana
  labels:
    type: local
spec:
  storageClassName: manual
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/tmp/pronosana"