apiVersion: v1
kind: Service
metadata:
  name: pronosana-grafana-service
  labels:
    run: pronosana-grafana-service
spec:
  type: NodePort
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30300
    name: grafana-port
  selector:
    app: pronosana-grafana