# config file version
apiVersion: 1

deleteDatasources:
  - name: Thanos
    orgId: 1

datasources:
- name: Thanos
  type: prometheus
  access: proxy
  orgId: 1
  url: http://pronosana-thanos-querier:19192
  basicAuth: true
  basicAuthUser: admin

  jsonData:
     tlsAuth: false
     tlsAuthWithCACert: false

  version: 1
  editable: true